version: "3"

dotenv: [".env"]

tasks:
  install:
    cmds:
      - uv sync --dev
      - uv run pre-commit install

  run:
    dir: clerk_api_demo
    cmds:
      - uv run reflex run

  run-docs:
    cmds:
      # Use non-default port to not clash with reflex backend
      - uv run mkdocs serve -a localhost:9000

  test:
    deps:
      - task: lint
      - task: typecheck
    cmds:
      - uv sync --dev
      - uv run playwright install chromium
      - uv run pytest

  lint:
    cmds:
      - uv run ruff check .

  typecheck:
    cmds:
      - uv run pyright

  bump-patch:
    desc: Bump patch version (e.g., 1.1.3 -> 1.1.4)
    cmds:
      - uvx hatch version patch
      - uv lock

  bump-minor:
    desc: Bump minor version (e.g., 1.1.3 -> 1.2.0)
    cmds:
      - uvx hatch version minor
      - uv lock

  bump-major:
    desc: Bump major version (e.g., 1.1.3 -> 2.0.0)
    cmds:
      - uvx hatch version major
      - uv lock

  publish:
    preconditions:
      - sh: git status
    cmds:
      - git diff --quiet --staged || (echo "There are staged changes. They must be committed first" && exit 1)
      - git diff --quiet || (echo "There are unstaged changes. They must be committed first." && exit 1)

      - uvx hatch version | xargs -I {} git tag -a v{} -m "Release v{}"
      - git push --follow-tags

  pre-commit-all:
    cmds:
      - uv run pre-commit run --all-files

  pre-commit-update:
    cmds:
      - uv run pre-commit autoupdate

  build-component:
    desc: Build the reflex component (generates .pyi stubs and package dist)
    cmds:
      # Generate .pyi files from custom_components to avoid scanning tests/demo dirs
      # This is the same as what `reflex component build` does, but selective to avoid
      # scanning tests/demo directories which causes ModuleNotFoundError (issue #5114)
      - cd custom_components && uv run python -m reflex.utils.pyi_generator reflex_clerk_api
      # Build package from root (same as `python -m build .` in reflex component build)
      - uv run python -m build .

  manual-publish:
    preconditions:
      # Check environment variable
      - sh: test -n "$PYPI_TOKEN"
        msg: "PYPI_TOKEN is not set -- Add PYPI_TOKEN=... to .env file"
    cmds:
      - echo "Publishing to PyPI"
      - task: build-component
      - uv publish --token $PYPI_TOKEN

  manual-publish-docs:
    cmds:
      - uv run mkdocs gh-deploy --force

  share:
    desc: Share the component via the reflex library
    cmds:
      - uv run reflex component share
